name: Stream Check (Backup)

on:
  schedule:
    - cron: "*/10 * * * *"

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: pip install -r requirements.txt
      - run: python check_stream.py
